=== daidi/XMLParseToTree/sample/HITCS.dtd
<?xml version="1.0" encoding='UTF-8'?> 
 
<!ELEMENT ComputerScience (faculty+)> 
 	<!ELEMENT faculty (facultyName,researchCenter+)> 
		<!ELEMENT facultyName (#PCDATA)> 
		<!ELEMENT researchCenter (centerName,professorList)> 
			<!ELEMENT centerName (#PCDATA)> 
			<!ELEMENT professorList (professor+)> 
				<!ELEMENT professor (name,gender,supervisorDoctoral)> 
					<!ELEMENT name (#PCDATA)> 
					<!ELEMENT gender (#PCDATA)> 
					<!ELEMENT supervisorDoctoral (#PCDATA)>

=== daidi/XMLParseToTree/sample/HITCS.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE ComputerScience SYSTEM "HITCS.dtd">
<ComputerScience>
	<faculty>
		<facultyName>计算机科学与工程系</facultyName>
		<researchCenter>
			<centerName>计算机科学技术研究所</centerName>
			<professorList>
				<professor>
					<name>杨孝宗</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>王宇颖</name>
					<gender>female</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>季振洲</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>郭茂祖</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>姜守旭</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>张田文</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>徐志明</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>崔刚</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>王玲</name>
					<gender>female</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>智能接口与人机交互研究中心</centerName>
			<professorList>
				<professor>
					<name>高文</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>赵德斌</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>韩纪庆</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>姚鸿勋</name>
					<gender>female</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>李海峰</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>语言技术研究中心</centerName>
			<professorList>
				<professor>
					<name>李生</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>赵铁军</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>王晓龙</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>关毅</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>徐志明</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>企业与服务智能计算研究中心</centerName>
			<professorList>
				<professor>
					<name>徐晓飞</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>战德臣</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>邓胜春</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>臧天仪</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>何霆</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>计算机网络与信息安全研究中心</centerName>
			<professorList>
				<professor>
					<name>方滨兴</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>胡铭曾</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>张宏莉</name>
					<gender>female</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>李东</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>杜小江</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
				<professor>
					<name>张伟哲</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>容错与移动计算研究中心</centerName>
			<professorList>
				<professor>
					<name>杨孝宗</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>左德承</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>吴智博</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>刘宏伟</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>周海鹰</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>海量数据计算研究中心</centerName>
			<professorList>
				<professor>
					<name>李建中</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>樊文飞</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>高宏</name>
					<gender>female</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>生物计算研究中心</centerName>
			<professorList>
				<professor>
					<name>王亚东</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>王宽全</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>邬向前</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>多智能体机器人研究中心</centerName>
			<professorList>
				<professor>
					<name>洪炳镕</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>朴松昊</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>模式识别研究中心</centerName>
			<professorList>
				<professor>
					<name>唐降龙</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>石大明</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>黄剑华</name>
					<gender>male</gender>
					<supervisorDoctoral>false</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>航天软件工程研究中心</centerName>
			<professorList>
				<professor>
					<name>马培军</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>苏小红</name>
					<gender>female</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>社会计算与信息检索研究中心</centerName>
			<professorList>
				<professor>
					<name>刘挺</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
				<professor>
					<name>秦兵</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
		<researchCenter>
			<centerName>信息对抗技术研究所</centerName>
			<professorList>
				<professor>
					<name>牛夏牧</name>
					<gender>male</gender>
					<supervisorDoctoral>true</supervisorDoctoral>
				</professor>
			</professorList>
		</researchCenter>
	</faculty>
</ComputerScience>
